version: '3.8'
services:
  dev-db:
    container_name: dance-app-dev-db-container
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: dance-app-dev
  test-db:
    container_name: dance-app-test-db-container
    image: postgres:16
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: dance-app-dev
  maildev:
    image: maildev/maildev
    ports:
      - '1025:1025'
      - '1080:1080'
    environment:
      MAILDEV_INCOMING_USER: username
      MAILDEV_INCOMING_PASS: password
